id: I17932588
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T05:43:09+00:00'
last_modified: '2022-06-08T13:00:55.200864+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG14627
  title: དཀོན་མཆོག་འཕན་དར་དང་ཀོང་སྤྲུལ་ཡོན་ཏན་རྒྱ་མཚོའི་རྣམ་ཐར།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    E227:
      image_group_id: I1KG15643
      title: ''
      total_pages: 468
      order: 1
      base_file: E227.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
