id: P006962
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1KG14627
  title: དཀོན་མཆོག་འཕན་དར་དང་ཀོང་སྤྲུལ་ཡོན་ཏན་རྒྱ་མཚོའི་རྣམ་ཐར།
  author: ''
  volumes:
    9a319ce7ce544ea0afbde7c953518c4d:
      image_group_id: I1KG15643
      title: ''
      volume_number: 1
      total_pages: 468
